AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Handler: app.lambda_handler
    Runtime: python3.12
    Architectures:
      - x86_64

Resources:
  HelloWorldGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: services/hello_world_get/
      Events:
        HelloWorldGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  HelloWorldPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/hello_world_post/
      Events:
        HelloWorldPost:
          Type: Api
          Properties:
            Path: /hello
            Method: post

  HelloWorldPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/hello_world_put/
      Events:
        HelloWorldPost:
          Type: Api
          Properties:
            Path: /hello
            Method: put

  HelloWorldDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/hello_world_delete/
      Events:
        HelloWorldPost:
          Type: Api
          Properties:
            Path: /hello
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldGetFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldGetFunction.Arn
  HelloWorldPostFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldPostFunction.Arn
  HelloWorldPutFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldPutFunction.Arn
  HelloWorldDeleteFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldDeleteFunction.Arn
  HelloWorldGetFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldPostFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldPutFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldDeleteFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn





