name: Deploy SAM app
on:
  push:
    branches:
      - main

jobs:
  transfer-toec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Setup sam cli
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build
        run: sam build --use-container

      - name: Deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
