name: Deploy to to EC2
on:
  push:
    branches:
      - main

jobs:
  transfer-toec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Transfer Files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."
          REMOTE_HOST: "ec2-65-2-34-117.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/app/"

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: "ec2-65-2-34-117.ap-south-1.compute.amazonaws.com"
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/app
            npm install
            pm2 restart all
